'''author gkarathanasis
option for AOD run'''

import FWCore.ParameterSet.Config as cms

muon = cms.EDAnalyzer('HIUPC_Analysis_noTriggerMatch_3Prong_FullAODAnalyzer',
        isMC=cms.bool(False),
        includeJets=cms.bool(False),
        era = cms.string('dummy'), # updated in run_muonAnalyzer_cfg.py
        genEventInfo = cms.InputTag('generator'),
        pileupInfo=cms.InputTag('addPileupInfo'),
        Rho=cms.InputTag('fixedGridRhoFastjetAll'),
        beamSpot=cms.InputTag('offlineBeamSpot'),
        vertices=cms.InputTag("offlinePrimaryVerticesRecovery"),
        muons=cms.InputTag("muons"),
        electrons=cms.InputTag("gedGsfElectrons"),
        photons=cms.InputTag("gedPhotons"),
        tracks=cms.InputTag("generalTracks"),
        CaloTowers = cms.InputTag("towerMaker"),
        Centrality= cms.InputTag("hiCentrality"),
        RecHits = cms.InputTag("QWzdcreco"),        
        SAmuons=cms.InputTag("standAloneMuons"),
        dSAmuons=cms.InputTag("displacedStandAloneMuons"),
        dGlmuons=cms.InputTag("displacedGlobalMuons"),
        staCosmic=cms.InputTag("cosmicMuons"),
        triggerResults=cms.InputTag("TriggerResults::HLT"),
        triggerObjects=cms.InputTag('hltTriggerSummaryAOD'),
        l1Matches = cms.InputTag("muonL1Info"),
        l1MatchesQuality = cms.InputTag("muonL1Info", "quality"),
        l1MatchesDeltaR = cms.InputTag("muonL1Info", "deltaR"),
        l1MatchesByQ = cms.InputTag("muonL1InfoByQ"),
        l1MatchesByQQuality = cms.InputTag("muonL1InfoByQ", "quality"),
        l1MatchesByQDeltaR = cms.InputTag("muonL1InfoByQ", "deltaR"),
        muonSimInfo = cms.InputTag("muonSimClassifier"),
        triggerPaths=cms.vstring(), # updated in run_muonAnalyzer_cfg.py
        tagFilters=cms.vstring(), # updated in run_muonAnalyzer_cfg.py
        probeFilters=cms.vstring(), # updated in run_muonAnalyzer_cfg.py
        probeSelectorNames=cms.vstring(), # updated in run_muonAnalyzer_cfg.py
        probeSelectorBits=cms.vuint32(), # updated in run_muonAnalyzer_cfg.py
        gen = cms.InputTag("genParticles"),
        rhoJetsNC = cms.InputTag("fixedGridRhoFastjetCentralNeutral"),
        PFCands = cms.InputTag("particleFlow"),
        jets = cms.InputTag("ak4PFJetsCHS"),
        jetCorrector = cms.InputTag("ak4PFCHSL1FastL2L3Corrector"),
        genJets = cms.InputTag("ak4GenJets"),
        deepCSVProbb = cms.InputTag("pfDeepCSVJetTags:probb"),
        deepCSVProbbb = cms.InputTag("pfDeepCSVJetTags:probbb"),
        deepFlavProbb = cms.InputTag("pfDeepFlavourJetTags:probb"),
        deepFlavProbbb = cms.InputTag("pfDeepFlavourJetTags:probbb"),
        trgDRwindow= cms.double(1.0), # dr winwow hlt mu/offline
        tagQuality = cms.uint32(0),
        tagSelection = cms.string("pt()>1 && abs(eta())<2.4"),
        tagElectronSelection = cms.string("pt()>1 && abs(eta())<2.4"),
        probeHPurity = cms.bool(False),
        probeSelection = cms.string("pt()>1 && abs(eta())<2.5"),
        probeSelectionSA = cms.string("pt()>0"),
        muonOnly = cms.bool(False), # allow only reco or pat Muon for probes
        probeMuonSelection = cms.string("pt()>0"), #string for probe (reco or pat Muon)
        pairMassMin = cms.double(0.0),
        pairMassMax = cms.double(999.0), # 9999.0 for high mass C&C
        pairDz = cms.double(-1),
        RequireVtxCreation = cms.bool(False),
        minSVtxProb = cms.double(-1),
        maxDzProbeTrkMuon = cms.double(1.0), # max Dz(mu1,mu2)
        maxRelPtProbeTrkMuon = cms.double(1.0),# max [pt(mu)-pt(trk)]/pt(trk) for probe/offline
        maxDRProbeTrkMuon =  cms.double(0.5), # max DR for probe/offline
        maxDzProbeTrkElectron = cms.double(1.0), # max Dz(mu1,mu2)
        maxRelPtProbeTrkElectron = cms.double(1.0),# max [pt(mu)-pt(trk)]/pt(trk) for probe/offline
        maxDRProbeTrkElectron =  cms.double(0.5), # max DR for probe/offline
        maxDzProbeTrkPFC = cms.double(1.0), # max Dz(mu1,mu2)
        maxRelPtProbeTrkPFC = cms.double(1.0),# max [pt(mu)-pt(trk)]/pt(trk) for probe/offline
        maxDRProbeTrkPFC =  cms.double(0.5), # max DR for probe/offline
        minPtTrkSA=cms.double(0.0),  # min Pt for trk matching for SA muons
        maxDzProbeTrkSAMuon = cms.double(1.0), # max Dz(trk,SAmu)
        maxRelPtProbeTrkSAMuon = cms.double(1.0),# max [pt(SAmu)-pt(trk)]/pt(trk) for probe/offline
        maxDRProbeTrkSAMuon =  cms.double(0.5), # max DR for trk / SA muon
        maxDRProbeTrkDSA =  cms.double(0.5), # max DR for general track and dSA
        minTrkPt_1Prong = cms.double(0),
        maxTrkEta_1Prong  = cms.double(2.5),
        maxTrkNum_1Prong = cms.int32(10),
        minTrkPt_3Prong = cms.double(0),
        maxTrkEta_3Prong  = cms.double(2.5),
        maxTrkNum_3Prong = cms.int32(10),
        maxTrkNum_Gen = cms.int32(10),
        min_3prong_pt  = cms.double(0),
        min_3prong_pt_primary  = cms.double(0),
        max_3prong_eta  = cms.double(2.5),
        require_3prong_HP_trk = cms.bool(True),
        max_3prong_chi2 = cms.double(100),
        min_3prong_trkhits = cms.int32(3),
        min_3prong_pt_sum  = cms.double(0),
        max_Dz_3prong  = cms.double(-1),    
        min_vtx_prob_3prong  = cms.double(-1),    
        maxTau3prongCandstoKeep  = cms.uint32(10),    
        momPdgId= cms.uint32(443),
        genRecoDrMatch = cms.double(0.03),
        saveTnPTree = cms.bool(True),
        save3prongTree = cms.bool(True),
        saveCutTree = cms.bool(False),
        keepelectrontags = cms.bool(True),
        keepmultipletags = cms.bool(True),
        keepMuons = cms.bool(True),
        keepElectrons = cms.bool(True),
        keepTracks = cms.bool(True),
        keepPFcands = cms.bool(True),
        keepPhotons = cms.bool(True),
        keepCaloTowers = cms.bool(True),
        keepZDC = cms.bool(True),
        debug = cms.int32(0),
        MCType = cms.string(""), # filled in test_run file
        propM1 = cms.PSet(
            useStation2 = cms.bool(False),
            useTrack = cms.string("tracker"),
            useState = cms.string("atVertex"),  # in AOD
            useSimpleGeometry = cms.bool(True), # use just one cylinder and two planes, not all the fancy chambers  
        ),                                                        
)

fullAODSequence=cms.Sequence(muon)
